vim.opt.encoding = "utf-8" -- Set proper encoding
vim.opt.fileencoding = "utf-8" -- Set proper file encoding
vim.g.have_nerd_font = true -- Enables Nerd Font
vim.opt.termguicolors = true -- Still dont know exactly
vim.opt.number = true -- Show line numbers
vim.opt.relativenumber = true -- Enables relative line numbers
vim.opt.scrolloff = 10 -- Minimal number of screen lines to keep above and below the cursor
vim.opt.mouse = "a"
vim.opt.clipboard = "unnamedplus" -- Sync clipboard between OS and Nvim buffers
vim.opt.breakindent = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.signcolumn = 'yes'
vim.opt.tabstop = 4 -- Sets tabsize
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
